development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://plasir_redis:6379/1" } %>


test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://plasir_redis:6379/1" } %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://plasir_redis:6379/1" } %>
  channel_prefix: app_production
